# 作者：晨星
"""helios 全量错误码常量与 HTTP 状态映射（ARCH C6 / §5）。

命名规范：``E_<MODULE>_<REASON>``，全部常量必须唯一且匹配 ``^E_[A-Z]+_[A-Z_]+$``。
该不变量由 ``core/tests/test_codes.py`` 用反射枚举全模块属性守护。
"""

from __future__ import annotations

import re


# --------------------------------------------------------------------------- core
E_CORE_BAD_INPUT = "E_CORE_BAD_INPUT"
E_CORE_NOT_FOUND = "E_CORE_NOT_FOUND"
E_CORE_CONFIG_INVALID = "E_CORE_CONFIG_INVALID"
E_CORE_INTERNAL = "E_CORE_INTERNAL"

# ------------------------------------------------------------------------- ingest
E_INGEST_BAD_INPUT = "E_INGEST_BAD_INPUT"
E_INGEST_PARSE_FAILED = "E_INGEST_PARSE_FAILED"
E_INGEST_EMPTY_CORPUS = "E_INGEST_EMPTY_CORPUS"
E_INGEST_NOT_FOUND = "E_INGEST_NOT_FOUND"
E_INGEST_INTERNAL = "E_INGEST_INTERNAL"

# -------------------------------------------------------------------------- chunk
E_CHUNK_BAD_INPUT = "E_CHUNK_BAD_INPUT"
E_CHUNK_EMPTY_TEXT = "E_CHUNK_EMPTY_TEXT"
E_CHUNK_SPAN_OUT_OF_RANGE = "E_CHUNK_SPAN_OUT_OF_RANGE"
E_CHUNK_INTERNAL = "E_CHUNK_INTERNAL"

# -------------------------------------------------------------------------- embed
E_EMBED_BAD_INPUT = "E_EMBED_BAD_INPUT"
E_EMBED_DIM_MISMATCH = "E_EMBED_DIM_MISMATCH"
E_EMBED_MODEL_MISSING = "E_EMBED_MODEL_MISSING"
E_EMBED_NET_DISABLED = "E_EMBED_NET_DISABLED"
E_EMBED_TIMEOUT = "E_EMBED_TIMEOUT"
E_EMBED_DEGRADED = "E_EMBED_DEGRADED"

# ------------------------------------------------------------------------ lexical
E_LEXICAL_BAD_INPUT = "E_LEXICAL_BAD_INPUT"
E_LEXICAL_EMPTY_CORPUS = "E_LEXICAL_EMPTY_CORPUS"
E_LEXICAL_NOT_FOUND = "E_LEXICAL_NOT_FOUND"
E_LEXICAL_INTERNAL = "E_LEXICAL_INTERNAL"

# ------------------------------------------------------------------------- vector
E_VECTOR_BAD_INPUT = "E_VECTOR_BAD_INPUT"
E_VECTOR_DIM_MISMATCH = "E_VECTOR_DIM_MISMATCH"
E_VECTOR_NOT_FOUND = "E_VECTOR_NOT_FOUND"
E_VECTOR_INDEX_CORRUPT = "E_VECTOR_INDEX_CORRUPT"
E_VECTOR_INTERNAL = "E_VECTOR_INTERNAL"

# --------------------------------------------------------------------------- fuse
E_FUSE_BAD_INPUT = "E_FUSE_BAD_INPUT"
E_FUSE_EMPTY_INPUT = "E_FUSE_EMPTY_INPUT"
E_FUSE_INTERNAL = "E_FUSE_INTERNAL"

# ------------------------------------------------------------------------- rerank
E_RERANK_BAD_INPUT = "E_RERANK_BAD_INPUT"
E_RERANK_MODEL_MISSING = "E_RERANK_MODEL_MISSING"
E_RERANK_NET_DISABLED = "E_RERANK_NET_DISABLED"
E_RERANK_TIMEOUT = "E_RERANK_TIMEOUT"
E_RERANK_INTERNAL = "E_RERANK_INTERNAL"

# ---------------------------------------------------------------------------- llm
E_LLM_BAD_INPUT = "E_LLM_BAD_INPUT"
E_LLM_CONTEXT_OVERFLOW = "E_LLM_CONTEXT_OVERFLOW"
E_LLM_MODEL_MISSING = "E_LLM_MODEL_MISSING"
E_LLM_TIMEOUT = "E_LLM_TIMEOUT"
E_LLM_NET_DISABLED = "E_LLM_NET_DISABLED"
E_LLM_INTERNAL = "E_LLM_INTERNAL"

# -------------------------------------------------------------------------- tools
E_TOOLS_BAD_EXPR = "E_TOOLS_BAD_EXPR"
E_TOOLS_UNSAFE_EXPR = "E_TOOLS_UNSAFE_EXPR"
E_TOOLS_DIV_ZERO = "E_TOOLS_DIV_ZERO"
E_TOOLS_OVERFLOW = "E_TOOLS_OVERFLOW"

# --------------------------------------------------------------------------- cite
E_CITE_PARSE_FAILED = "E_CITE_PARSE_FAILED"
E_CITE_NOT_FOUND = "E_CITE_NOT_FOUND"
E_CITE_ALIGN_FAILED = "E_CITE_ALIGN_FAILED"
E_CITE_INTERNAL = "E_CITE_INTERNAL"

# ----------------------------------------------------------------------- pipeline
E_PIPE_BAD_INPUT = "E_PIPE_BAD_INPUT"
E_PIPE_NOT_FOUND = "E_PIPE_NOT_FOUND"
E_PIPE_STAGE_FAILED = "E_PIPE_STAGE_FAILED"
E_PIPE_TIMEOUT = "E_PIPE_TIMEOUT"
E_PIPE_INTERNAL = "E_PIPE_INTERNAL"

# ---------------------------------------------------------------------------- api
E_API_BAD_REQUEST = "E_API_BAD_REQUEST"
E_API_NOT_FOUND = "E_API_NOT_FOUND"
E_API_RATE_LIMITED = "E_API_RATE_LIMITED"
E_API_STREAM_FAILED = "E_API_STREAM_FAILED"
E_API_INTERNAL = "E_API_INTERNAL"

# ------------------------------------------------------------------------- evalkit
E_EVAL_BAD_INPUT = "E_EVAL_BAD_INPUT"
E_EVAL_GOLD_INVALID = "E_EVAL_GOLD_INVALID"
E_EVAL_FIXTURE_STALE = "E_EVAL_FIXTURE_STALE"
E_EVAL_INTERNAL = "E_EVAL_INTERNAL"

#: 全量错误码（顺序稳定，供反射守护测试枚举比对）。
ALL_CODES: tuple[str, ...] = (
    E_CORE_BAD_INPUT, E_CORE_NOT_FOUND, E_CORE_CONFIG_INVALID, E_CORE_INTERNAL,
    E_INGEST_BAD_INPUT, E_INGEST_PARSE_FAILED, E_INGEST_EMPTY_CORPUS, E_INGEST_NOT_FOUND,
    E_INGEST_INTERNAL, E_CHUNK_BAD_INPUT, E_CHUNK_EMPTY_TEXT, E_CHUNK_SPAN_OUT_OF_RANGE,
    E_CHUNK_INTERNAL, E_EMBED_BAD_INPUT, E_EMBED_DIM_MISMATCH, E_EMBED_MODEL_MISSING,
    E_EMBED_NET_DISABLED, E_EMBED_TIMEOUT, E_EMBED_DEGRADED, E_LEXICAL_BAD_INPUT,
    E_LEXICAL_EMPTY_CORPUS, E_LEXICAL_NOT_FOUND, E_LEXICAL_INTERNAL, E_VECTOR_BAD_INPUT,
    E_VECTOR_DIM_MISMATCH, E_VECTOR_NOT_FOUND, E_VECTOR_INDEX_CORRUPT, E_VECTOR_INTERNAL,
    E_FUSE_BAD_INPUT, E_FUSE_EMPTY_INPUT, E_FUSE_INTERNAL, E_RERANK_BAD_INPUT,
    E_RERANK_MODEL_MISSING, E_RERANK_NET_DISABLED, E_RERANK_TIMEOUT, E_RERANK_INTERNAL,
    E_LLM_BAD_INPUT, E_LLM_CONTEXT_OVERFLOW, E_LLM_MODEL_MISSING, E_LLM_TIMEOUT,
    E_LLM_NET_DISABLED, E_LLM_INTERNAL, E_TOOLS_BAD_EXPR, E_TOOLS_UNSAFE_EXPR,
    E_TOOLS_DIV_ZERO, E_TOOLS_OVERFLOW, E_CITE_PARSE_FAILED, E_CITE_NOT_FOUND,
    E_CITE_ALIGN_FAILED, E_CITE_INTERNAL, E_PIPE_BAD_INPUT, E_PIPE_NOT_FOUND,
    E_PIPE_STAGE_FAILED, E_PIPE_TIMEOUT, E_PIPE_INTERNAL, E_API_BAD_REQUEST,
    E_API_NOT_FOUND, E_API_RATE_LIMITED, E_API_STREAM_FAILED, E_API_INTERNAL,
    E_EVAL_BAD_INPUT, E_EVAL_GOLD_INVALID, E_EVAL_FIXTURE_STALE, E_EVAL_INTERNAL,
)

#: 错误码 -> HTTP 状态码（ARCH §5 逐项一致，由 core/tests/test_errors.py 断言）。
HTTP_STATUS: dict[str, int] = {
    E_CORE_BAD_INPUT: 400, E_CORE_NOT_FOUND: 404, E_CORE_CONFIG_INVALID: 400, E_CORE_INTERNAL: 500,
    E_INGEST_BAD_INPUT: 400, E_INGEST_PARSE_FAILED: 422, E_INGEST_EMPTY_CORPUS: 422,
    E_INGEST_NOT_FOUND: 404, E_INGEST_INTERNAL: 500, E_CHUNK_BAD_INPUT: 400,
    E_CHUNK_EMPTY_TEXT: 422, E_CHUNK_SPAN_OUT_OF_RANGE: 500, E_CHUNK_INTERNAL: 500,
    E_EMBED_BAD_INPUT: 400, E_EMBED_DIM_MISMATCH: 500, E_EMBED_MODEL_MISSING: 503,
    E_EMBED_NET_DISABLED: 403, E_EMBED_TIMEOUT: 504, E_EMBED_DEGRADED: 503,
    E_LEXICAL_BAD_INPUT: 400, E_LEXICAL_EMPTY_CORPUS: 422, E_LEXICAL_NOT_FOUND: 404,
    E_LEXICAL_INTERNAL: 500, E_VECTOR_BAD_INPUT: 400, E_VECTOR_DIM_MISMATCH: 400,
    E_VECTOR_NOT_FOUND: 404, E_VECTOR_INDEX_CORRUPT: 500, E_VECTOR_INTERNAL: 500,
    E_FUSE_BAD_INPUT: 400, E_FUSE_EMPTY_INPUT: 422, E_FUSE_INTERNAL: 500,
    E_RERANK_BAD_INPUT: 400, E_RERANK_MODEL_MISSING: 503, E_RERANK_NET_DISABLED: 403,
    E_RERANK_TIMEOUT: 504, E_RERANK_INTERNAL: 500, E_LLM_BAD_INPUT: 400,
    E_LLM_CONTEXT_OVERFLOW: 400, E_LLM_MODEL_MISSING: 503, E_LLM_TIMEOUT: 504,
    E_LLM_NET_DISABLED: 403, E_LLM_INTERNAL: 500, E_TOOLS_BAD_EXPR: 422,
    E_TOOLS_UNSAFE_EXPR: 422, E_TOOLS_DIV_ZERO: 422, E_TOOLS_OVERFLOW: 422,
    E_CITE_PARSE_FAILED: 422, E_CITE_NOT_FOUND: 404, E_CITE_ALIGN_FAILED: 422,
    E_CITE_INTERNAL: 500, E_PIPE_BAD_INPUT: 400, E_PIPE_NOT_FOUND: 404,
    E_PIPE_STAGE_FAILED: 500, E_PIPE_TIMEOUT: 504, E_PIPE_INTERNAL: 500,
    E_API_BAD_REQUEST: 400, E_API_NOT_FOUND: 404, E_API_RATE_LIMITED: 429,
    E_API_STREAM_FAILED: 500, E_API_INTERNAL: 500, E_EVAL_BAD_INPUT: 400,
    E_EVAL_GOLD_INVALID: 422, E_EVAL_FIXTURE_STALE: 500, E_EVAL_INTERNAL: 500,
}

#: 错误码命名规范；所有常量必须匹配，否则视为非法（ARCH C6）。
CODE_PATTERN: re.Pattern[str] = re.compile(r"^E_[A-Z]+_[A-Z_]+$")

#: 不可恢复的错误原因后缀（ARCH §5「可恢复」列为「否」的项），用于推导默认 recoverable。
NON_RECOVERABLE_REASONS: frozenset[str] = frozenset(
    {"CONFIG_INVALID", "DIM_MISMATCH", "SPAN_OUT_OF_RANGE", "GOLD_INVALID", "FIXTURE_STALE"}
)

DEFAULT_HTTP_STATUS = 500


def is_known_code(code: str) -> bool:
    """判断错误码是否为已登记常量。"""
    return code in HTTP_STATUS


def http_status(code: str) -> int:
    """返回错误码对应的 HTTP 状态码；未知码一律 500（E_*_INTERNAL 语义）。"""
    return HTTP_STATUS.get(code, DEFAULT_HTTP_STATUS)


def default_recoverable(code: str) -> bool:
    """按错误码推导默认可恢复标志：不可恢复后缀命中则为 False，否则 True。"""
    reason = code.rsplit("_", 1)[-1]
    return reason not in NON_RECOVERABLE_REASONS


def net_disabled_code(component: str) -> str:
    """把组件名映射为对应的 ``E_*_NET_DISABLED`` 错误码。

    component 取值为 ``embed`` / ``rerank`` / ``llm``；未知组件回落 ``E_CORE_INTERNAL``。
    """
    table = {"embed": E_EMBED_NET_DISABLED, "rerank": E_RERANK_NET_DISABLED, "llm": E_LLM_NET_DISABLED}
    return table.get(component, E_CORE_INTERNAL)
